Django-Project1/ParserHH/ParserHH/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('parserHHapp.urls', namespace='parserHHapp'))
]

Django-Project1/ParserHH/parserHHapp/urls.py
from django.urls import path
from parserHHapp import views

app_name = 'parserHHapp'

urlpatterns = [
    path('', views.start, name='index'),
    path('form/', views.form, name='form'),
    path('about/', views.about, name='about')
]

Django-Project1/ParserHH/parserHHapp/models.py
from django.db import models
from django.db.models import Model, CharField, TextField, DateTimeField, ForeignKey
from django.db.models import ManyToManyField, URLField, FloatField, IntegerField




class Word(Model):
    word = CharField(max_length=30, verbose_name='Запрос')
    count = IntegerField(verbose_name='Количество')
    up = FloatField(verbose_name="Верхняя граница")
    down = FloatField(verbose_name='Нижняя граница')

class Skill(Model):
        name = CharField(max_length=50, verbose_name='Навык')

        def __str__(self):
            return self.name

class Wordskill(Model):
        id_word = ForeignKey(Word, on_delete=models.CASCADE)
        id_skill = ForeignKey(Skill, on_delete=models.CASCADE)
        count = FloatField()
        percent = FloatField()

class Type(Model):
    name = CharField(max_length=10, unique=True)


class Vacancy(Model):
    published = DateTimeField()
    name = CharField(max_length=50)
    url = URLField()
    word_id = ForeignKey(Word, on_delete=models.CASCADE)
    # area = ForeignKey(Area, on_delete=models.CASCADE)
    # schedule = ForeignKey(Schedule, on_delete=models.CASCADE)
    snippet = TextField()
    salaryFrom = FloatField(default=0)
    salaryTo = FloatField(default=0)
    # employer = ForeignKey(Employer, on_delete=models.CASCADE)
    type = ForeignKey(Type, on_delete=models.CASCADE)

Django-Project1/ParserHH/parserHHapp/forms.py
from django import forms


class ReqForm(forms.Form):
    vacancy = forms.CharField(label='Строка поиска ')
    where = forms.ChoiceField(label='Где искать ', choices=[('all', "Везде"),
                                                            ('company', 'В названии компании'),
                                                            ('name', 'В названии вакансии')])
    pages = forms.IntegerField(label='Количество анализируемых страниц ', initial=3)

Django-Project1/ParserHH/parserHHapp/views.py
from django.shortcuts import render
from .forms import ReqForm
from .models import Word, Wordskill, Vacancy
from parserHHapp.management.commands.full_db import Command


# Create your views here.
def start(request):
    return render(request, 'parserHHapp/index.html')

def form(request):
    form1 = ReqForm
    return render(request, 'parserHHapp/form.html', context={'form': form1})


def about(request):
    if request.method == 'POST':
        form = ReqForm(request.POST)
        if form.is_valid():
            vac = form.cleaned_data['vacancy']
            where = form.cleaned_data['where']
            pages = form.cleaned_data['pages']
            print(vac, where, pages, sep='\n')
            com = Command(vac, pages, where)
            com.handle()
            v = Word.objects.get(word=vac)
            s = Wordskill.objects.filter(id_word_id=v.id).all()
            vac = Vacancy.objects.filter(word_id=v).all()
            print(vac, v, s, sep='\n')
            return render(request, 'parserHHapp/about.html', context={'vac': vac, 'word': v, 'skills': s})
        else:
            form1 = ReqForm
            return render(request, 'parserHHapp/form.html', context={'form': form1})

Django-Project1/ParserHH/parserHHapp/templates/parserHHapp/about.html
{% extends "base.html" %}
    <head>
{% block title %} Результат {% endblock %}
    </head>
    <body>

         <header>
            <h1 class="site-heading text-center text-faded d-none d-lg-block">
                <span class="site-heading-upper text-primary mb-3">Результаты</span>
            </h1>
        </header>
        <!-- Page Content-->
        {% block content %}
        <section class="page-section about-heading">
            <div class="container" >
                <div class="about-heading-content">
                    <div class="row">
                        <div class="col-xl-5 col-lg-4 mx-auto" >
                            <div class="bg-faded rounded p-5" >
                                <br>
                                <br>
                                <br>
                                <br>
                                <br>
                                <br>
                                <br>
                                <br>
                                <br>
                                <br>

                                <table class="table" >
                                    <thead class="thead">
                                        <tr>
                                            <th scope="row">Вакансия: {{ word.word }}</th>
                                            <th scope="row">Условия: {{ item.schedule.name }}</th>
                                            <th scope="row">Ср. верхняя граница: {{ word.up }}руб.</th>
                                            <th scope="row">Ср. нижняя граница: {{ word.down }}руб.</th>

                                        </tr>
                                    </thead>
                                    <tbody>
                                <table class="table" >
                                    <thead class="thead">
                                        <tr>
                                            <th scope="col">Номер</th>
                                            <th scope="col">Название</th>
                                            <th scope="col">Процент упоминаний</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                          {% for item in skills %}
                                            <tr>
                                                <th scope="row">{{ forloop.counter }} </th>
                                                <td>{{ item.id_skill.name }}</td>
                                                <td align="right">{{ item.percent }}%</td>
                                            </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        {% endblock %}

    </body>

Django-Project1/ParserHH/parserHHapp/templates/parserHHapp/form.html
{% extends "base.html" %}
    <head>
{% block title %} Поиск {% endblock %}
    </head>
    <body>
         <header>
 {% block header %} Форма для поиска {% endblock %}
        </header>
{% block content %}
        <section class="projects-section bg-light" id="projects">
            <div class="container px-4 px-lg-5">
                <!-- Featured Project Row-->
                <div class="row gx-0 mb-4 mb-lg-5 align-items-center">
                    <div class="col-xl-8 col-lg-7"><img class="img-fluid mb-3 mb-lg-0" src="/static/assets/img/glav1.png" alt="..." /></div>

                    <div class="col-xl-4 col-lg-5">
                        <div class="featured-text text-center text-lg-left">
                            <h3>Поиск</h3>
                            <p class="text-black-50 mb-0">

                            <form action="{% url 'parserHHapp:about' %}" method="post">
                            {% csrf_token %}
                              <div class="form-group">
                                <label for="vacancy">Текст поиска:</label>
                                     <br>
                                     <br>
                                <input type="text" name="vacancy" placeholder="Строка поиска" class="form-control" id="vacancy">
                                     <br>
                                     <br>
                                <label for="wh">Где искать:</label>
                                <select name="where" class="form-control" id="wh">
                                    <option value="all">Везде</option>
                                    <option value="company">В названии компании</option>
                                    <option selected value="name">В названии вакансии</option>
                                </select>
                                  <br>
                                  <br>
                                <label for="p">Количество анализируемых страниц</label>
                                <input type="number" name="pages" value="3" class="form-control" id="p">
                                <input type="submit" value="Искать вакансию" class="btn btn-primary">
                               </div>
                            </form>
                        </div>
                     </div>
                </div>
            </div>
        </section>
  {% endblock %}

    </body>

Django-Project1/ParserHH/parserHHapp/templates/parserHHapp/index.html
{% extends "base.html" %}
{% block title %} МегаПарсер НН {% endblock %}
{% block header %} МегаПарсер HH {% endblock %}

<body>
        <!-- Page Content-->
        {% block content %}
        <section>
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5">
                    <div class="col-lg-6">
                        <h1 class="mt-5">Мегапарсер hh</h1>
                        <h2 class="mx-auto mt-2 mb-5">Поиск вакансий на сайте hh.ru, анализ требований, уровень зарплат</h2>
                        <div class="intro-button mx-auto">
                            <a class="btn btn-primary btn-xl" href="/form">Приступить!</a>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        {% endblock %}
    </body>

Django-Project1/ParserHH/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>{% block title %}{% endblock %}</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href= "{% static '/assets/favicon.ico' %}"/>
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static '/css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-bottom">
            <div class="container px-4 px-lg-5">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item active"><a class="nav-link" href="{% url 'parserHHapp:index' %}">Главная</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'parserHHapp:form' %}">Поиск</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <h1>{% block header %}{% endblock %}</h1>
        <!-- Page Content-->

        {% block content %}
        {% endblock %}

        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js'%}"></script>
    </body>
</html>